# Generated by Django 5.0.6 on 2024-06-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cargos',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cargos',
            field=models.ManyToManyField(to='autenticacao.cargos'),
        ),
    ]
